# Generated by Django 2.2.3 on 2019-10-09 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
