# Generated by Django 2.1.3 on 2019-04-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Group')),
            ],
            options={
                'verbose_name': 'Подгруппа студента',
                'verbose_name_plural': 'Подгруппы студентов',
            },
        ),
    ]
