# Generated by Django 2.2.3 on 2019-09-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='university.Group'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='university.Faculty'),
        ),
        migrations.AddField(
            model_name='group',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.Occupation'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.ClassTime'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.Lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Timetbale'),
        ),
        migrations.AlterUniqueTogether(
            name='timetbale',
            unique_together={('subgroup', 'type_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'subgroup')},
        ),
        migrations.AlterUniqueTogether(
            name='occupation',
            unique_together={('title', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_time', 'weekday')},
        ),
    ]
