# Generated by Django 2.1.3 on 2019-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='occupations',
            field=models.ManyToManyField(blank=True, to='university.Occupation'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='groups',
            field=models.ManyToManyField(blank=True, to='university.Group'),
        ),
    ]
