# Generated by Django 2.2.3 on 2019-09-17 10:31

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('university', '0002_auto_20190916_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='class',
            name='modified_timestamp',
        ),
        migrations.RemoveField(
            model_name='timetbale',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='timetbale',
            name='modified_timestamp',
        ),
        migrations.AddField(
            model_name='class',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True,
                                                                    default=django.utils.timezone.now,
                                                                    verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True,
                                                                    default=django.utils.timezone.now,
                                                                    verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='timetbale',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True,
                                                                    default=django.utils.timezone.now,
                                                                    verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetbale',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.ForeignKey(help_text='Время начала занятия', on_delete=django.db.models.deletion.PROTECT,
                                    to='university.ClassTime'),
        ),
        migrations.AlterField(
            model_name='class',
            name='type_of_class',
            field=models.SmallIntegerField(choices=[(0, 'Практическое занятие'), (1, 'Лекция')],
                                           help_text='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='timetbale',
            name='type_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Числитель'), (1, 'Знаменатель')], help_text='Тип недели'),
        ),
    ]
