# Generated by Django 2.1.3 on 2019-04-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='occupations',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.Occupation'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='university.Faculty'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='university.Group'),
        ),
    ]
