# Generated by Django 2.2.3 on 2019-09-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20190917_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('timetable', 'class_time', 'weekday')},
        ),
    ]
