# Generated by Django 2.1.3 on 2019-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
