# Generated by Django 2.2.3 on 2019-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20190924_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
