# Generated by Django 2.2.3 on 2019-10-15 12:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('university', '0006_auto_20190925_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='current_type_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Numerator'), (1, 'Denominator')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetbale',
            name='type_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Numerator'), (1, 'Denominator')], help_text='Тип недели'),
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
