# Generated by Django 2.1.3 on 2019-05-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20190420_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type_of_class', models.SmallIntegerField(choices=[(0, 'Практическое занятие'), (1, 'Лекция')])),
                ('classroom', models.CharField(max_length=10)),
                ('weekday', models.SmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TimeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetbale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_week', models.SmallIntegerField(choices=[(0, 'Числитель'), (1, 'Знаменатель')])),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Subgroup')),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='short_title',
        ),
        migrations.AlterUniqueTogether(
            name='occupation',
            unique_together={('title', 'code')},
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.Lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='time_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.TimeClass'),
        ),
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Timetbale'),
        ),
    ]
