# Generated by Django 2.2.3 on 2019-10-21 12:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('university', '0007_auto_20191015_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='current_type_of_week',
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
