# Generated by Django 2.1.3 on 2019-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20190502_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeClass',
            new_name='ClassTime',
        ),
    ]
