# Generated by Django 2.2.3 on 2019-10-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20191021_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='classtime',
            options={'verbose_name': 'Number of class', 'verbose_name_plural': 'Numbers of classes'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group of student', 'verbose_name_plural': 'Groups of students'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'Subgroup of student', 'verbose_name_plural': 'Subgroups of students'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timetbale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='universityinfo',
            options={'verbose_name_plural': 'University Info'},
        ),
        migrations.AddField(
            model_name='class',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='timetbale',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
    ]
