# Generated by Django 2.2.3 on 2019-08-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20190715_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='time_class',
            new_name='class_time',
        ),
    ]
