# Generated by Django 2.2.3 on 2019-10-29 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('university', '0009_auto_20191026_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
