# Generated by Django 2.2.3 on 2019-11-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20191029_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timetbale',
            new_name='Timetable',
        ),
    ]
