# Generated by Django 2.2.3 on 2019-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20190816_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_time', 'weekday')},
        ),
    ]
